### ISSUE TITLE
AttributeError: 'Legend' object has no attribute 'draggable' 

### ISSUE THREAD

**Issue by sdclaro** [semiautomaticgit/SemiAutomaticClassificationPlugin#114]
Traceback (most recent call last):
  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\semiautomaticclassificationplugin.py", line 1296, in newProjectLoaded
    cfg.utls.clearTable(cfg.uiscp.scatter_list_plot_tableWidget)
  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\spectralsignature\spectralsignatureplot.py", line 463, in refreshPlot
    self.signaturePlot()
  File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\spectralsignature\spectralsignatureplot.py", line 711, in signaturePlot
    # matplotlib API Changes for 3.1.1
AttributeError: 'Legend' object has no attribute 'draggable'

I get this error every time I open QGIS. I am using QGIS 3.14 now but I'm getting the same error with QGIS 3.10. I use SCP 6.4.6.

**Comment by semiautomaticgit** [comment]
Hello, 
unfortunately I can't reproduce the issue.
Please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by sdclaro** [comment]
Hi. I upgraded to QGIS 3.14.1 and deleted older versions in my computer. It works fine now. Sorry for the trouble.
