### ISSUE TITLE
Getting error while clipping rasters

### ISSUE THREAD

**Issue by rahulkgour** [semiautomaticgit/SemiAutomaticClassificationPlugin#144]
**Getting below error**

2020-12-04T21:50:04     WARNING    Traceback (most recent call last):
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 82, in clipRastersAction
              self.clipRasters()
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 223, in clipRasters
              cfg.utls.GDALCopyRaster(vrtCheck, f, 'GTiff', cfg.rasterCompression, 'LZW')
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/core/utils.py", line 7340, in GDALCopyRaster
              manager = cfg.MultiManagerSCP()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/context.py", line 56, in Manager
              m.start()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/managers.py", line 547, in start
              self._address = reader.recv()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/connection.py", line 250, in recv
              buf = self._recv_bytes()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
              buf = self._recv(4)
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
              raise EOFError
             EOFError
             
2020-12-04T22:01:19     WARNING    Traceback (most recent call last):
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 82, in clipRastersAction
              self.clipRasters()
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 223, in clipRasters
              cfg.utls.GDALCopyRaster(vrtCheck, f, 'GTiff', cfg.rasterCompression, 'LZW')
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/core/utils.py", line 7340, in GDALCopyRaster
              manager = cfg.MultiManagerSCP()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/context.py", line 56, in Manager
              m.start()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/managers.py", line 547, in start
              self._address = reader.recv()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/connection.py", line 250, in recv
              buf = self._recv_bytes()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
              buf = self._recv(4)
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
              raise EOFError
             EOFError

**Comment by semiautomaticgit** [comment]
Hello, it seems an installation issue, but I'll look into this

**Comment by rahulkgour** [comment]
> Hello, it seems an installation issue, but I'll look into this

thanks for your response.
If possible can you guide me with the right installation process, as I have tried re-installing the QGIS and SCP like any other software and plugins.
I did install Pythons latest version manually i.s. 3.9

You help will be highly appreciable.

**Comment by semiautomaticgit** [comment]
The installation process should be very easy, unfortunately I think it is an issue specific of the operating system and QGIS version. 
You could try to install a different QGIS version, and a previous Python version.

**Comment by rahulkgour** [comment]
Hi,

As you suggested I tried different version of QGIS with earlier version of Python, but issue persists.

Now, I have installed most stable LTR QGIS 10 and Python 3.8.6, even I updated the latest SCP plugin today.
I can still see the error (**I can see that error have 'python3.7' but as I mentioned I have installed python version as 3.8.6. Is there any issue while reading the python files?**).


2020-12-07T19:15:11     WARNING    warning:/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/semaphore_tracker.py:55: UserWarning: semaphore_tracker: process died unexpectedly, relaunching. Some semaphores might leak.
              warnings.warn('semaphore_tracker: process died unexpectedly, '
             
             traceback: File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/threading.py", line 885, in _bootstrap
              self._bootstrap_inner()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/threading.py", line 917, in _bootstrap_inner
              self.run()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/threading.py", line 865, in run
              self._target(*self._args, **self._kwargs)
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/pool.py", line 412, in _handle_workers
              pool._maintain_pool()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/pool.py", line 248, in _maintain_pool
              self._repopulate_pool()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
              w.start()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/process.py", line 112, in start
              self._popen = self._Popen(self)
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
              return Popen(process_obj)
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
              super().__init__(process_obj)
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
              self._launch(process_obj)
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 40, in _launch
              tracker_fd = semaphore_tracker.getfd()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/semaphore_tracker.py", line 35, in getfd
              self.ensure_running()
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/multiprocessing/semaphore_tracker.py", line 55, in ensure_running
              warnings.warn('semaphore_tracker: process died unexpectedly, '

**Comment by rahulkgour** [comment]
**_Pasting Python Messagings as well which I retrieved during loading of SCP plugin, may be of some help.
And I exclusively installed 'matplotlib' through Mac terminal._**


2020-12-07T19:56:48     WARNING    warning:/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/pyparsing.py:3077: DeprecationWarning: invalid escape sequence \w
              """
             
             traceback: File "", line 1, in 
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 354, in startPlugin
              if not _startPlugin(packageName):
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/__init__.py", line 65, in classFactory
              from .semiautomaticclassificationplugin import SemiAutomaticClassificationPlugin
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/semiautomaticclassificationplugin.py", line 83, in 
              from .ui.semiautomaticclassificationplugindialog import SemiAutomaticClassificationPluginDialog
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/ui/semiautomaticclassificationplugindialog.py", line 39, in 
              from .ui_semiautomaticclassificationplugin_scatter_plot import Ui_ScatterPlot
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/ui/ui_semiautomaticclassificationplugin_scatter_plot.py", line 459, in 
              from .scatterwidget2 import ScatterWidget2
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/ui/scatterwidget2.py", line 39, in 
              import matplotlib
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/matplotlib/__init__.py", line 141, in 
              from . import cbook, rcsetup
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1035, in _handle_fromlist
              File "", line 219, in _call_with_frames_removed
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/matplotlib/rcsetup.py", line 25, in 
              from matplotlib.fontconfig_pattern import parse_fontconfig_pattern
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/matplotlib/fontconfig_pattern.py", line 19, in 
              from pyparsing import (Literal, ZeroOrMore, Optional, Regex, StringEnd,
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 724, in exec_module
              File "", line 860, in get_code
              File "", line 791, in source_to_code
              File "", line 219, in _call_with_frames_removed
             
2020-12-07T19:56:52     WARNING    warning:/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/qgis_proj_helper.py:8: DeprecationWarning: QgsCoordinateReferenceSystem constructor is deprecated
              CRS_3857 = QgsCoordinateReferenceSystem(3857)
             
             traceback: File "", line 1, in 
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 354, in startPlugin
              if not _startPlugin(packageName):
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/__init__.py", line 34, in classFactory
              from .quick_map_services import QuickMapServices
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/quick_map_services.py", line 40, in 
              from .qgis_map_helpers import add_layer_to_map
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/qgis_map_helpers.py", line 17, in 
              from .py_tiled_layer.tilelayer import TileLayer
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/py_tiled_layer/tilelayer.py", line 36, in 
              from ..qgis_proj_helper import ProjectionHelper
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/qgis_proj_helper.py", line 7, in 
              class ProjectionHelper:
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/qgis_proj_helper.py", line 8, in ProjectionHelper
              CRS_3857 = QgsCoordinateReferenceSystem(3857)
             
2020-12-07T19:56:52     WARNING    warning:/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/py_tiled_layer/tilelayer.py:64: DeprecationWarning: QgsCoordinateReferenceSystem constructor is deprecated
              CRS_3857 = QgsCoordinateReferenceSystem(3857)
             
             traceback: File "", line 1, in 
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 354, in startPlugin
              if not _startPlugin(packageName):
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/__init__.py", line 34, in classFactory
              from .quick_map_services import QuickMapServices
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/quick_map_services.py", line 40, in 
              from .qgis_map_helpers import add_layer_to_map
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/qgis_map_helpers.py", line 17, in 
              from .py_tiled_layer.tilelayer import TileLayer
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/py_tiled_layer/tilelayer.py", line 62, in 
              class TileLayer(QgsPluginLayer):
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/py_tiled_layer/tilelayer.py", line 64, in TileLayer
              CRS_3857 = QgsCoordinateReferenceSystem(3857)
             
2020-12-07T19:56:52     WARNING    warning:/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/rb_result_renderer.py:35: DeprecationWarning: QgsCoordinateReferenceSystem constructor is deprecated
              self.srs_wgs84 = QgsCoordinateReferenceSystem(4326)
             
             traceback: File "", line 1, in 
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 359, in startPlugin
              plugins[packageName].initGui()
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/quick_map_services.py", line 121, in initGui
              self.init_server_panel()
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/quick_map_services.py", line 311, in init_server_panel
              self.server_toolbox = QmsServiceToolbox(self.iface)
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/qms_service_toolbox.py", line 135, in __init__
              self.extent_renderer = RubberBandResultRenderer()
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/rb_result_renderer.py", line 35, in __init__
              self.srs_wgs84 = QgsCoordinateReferenceSystem(4326)
             
2020-12-07T19:56:53     WARNING    warning:/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
              InsecureRequestWarning)
             
             traceback: File "", line 1, in 
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 359, in startPlugin
              plugins[packageName].initGui()
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/quick_map_services.py", line 121, in initGui
              self.init_server_panel()
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/quick_map_services.py", line 311, in init_server_panel
              self.server_toolbox = QmsServiceToolbox(self.iface)
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/qms_service_toolbox.py", line 155, in __init__
              self.show_news()
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/qms_service_toolbox.py", line 160, in show_news
              qms_news = client.get_news()
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/quick_map_services/qms_external_api_python/api/api_abstract.py", line 64, in get_news
              response = get(url, verify=False)
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/requests/api.py", line 75, in get
              return request('get', url, params=params, **kwargs)
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/requests/api.py", line 60, in request
              return session.request(method=method, url=url, **kwargs)
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/requests/sessions.py", line 533, in request
              resp = self.send(prep, **send_kwargs)
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/requests/sessions.py", line 646, in send
              r = adapter.send(request, **kwargs)
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/requests/adapters.py", line 449, in send
              timeout=timeout
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/urllib3/connectionpool.py", line 603, in urlopen
              chunked=chunked)
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/urllib3/connectionpool.py", line 344, in _make_request
              self._validate_conn(conn)
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/urllib3/connectionpool.py", line 851, in _validate_conn
              InsecureRequestWarning)
             
2020-12-07T19:56:57     WARNING    warning:/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/matplotlib/cbook/__init__.py:424: MatplotlibDeprecationWarning: 
             Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.
              warn_deprecated("2.2", "Passing one of 'on', 'true', 'off', 'false' as a "
             
             traceback: File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/semiautomaticclassificationplugin.py", line 1526, in newProjectLoaded
              self.resetSCP()
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/semiautomaticclassificationplugin.py", line 1435, in resetSCP
              cfg.spSigPlot.refreshPlot()
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/spectralsignature/spectralsignatureplot.py", line 463, in refreshPlot
              self.signaturePlot()
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/spectralsignature/spectralsignatureplot.py", line 646, in signaturePlot
              cfg.uisp.Sig_Widget.sigCanvas.ax.grid('on')
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/matplotlib/axes/_base.py", line 2761, in grid
              b = _string_to_bool(b)
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/matplotlib/cbook/__init__.py", line 424, in _string_to_bool
              warn_deprecated("2.2", "Passing one of 'on', 'true', 'off', 'false' as a "
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/matplotlib/cbook/deprecation.py", line 112, in warn_deprecated
              warnings.warn(message, category, stacklevel=2)

**Comment by semiautomaticgit** [comment]
Thank you @rahulkgour .
I think this issue is related to this https://github.com/qgis/QGIS/issues/40472.
Could you please try with QGIS 3.16?

**Comment by rahulkgour** [comment]
> Thank you @rahulkgour .
> I think this issue is related to this [qgis/QGIS#40472](https://github.com/qgis/QGIS/issues/40472).
> Could you please try with QGIS 3.16?

Sure @semiautomaticgit, I will try with QGIS 3.16 and update you soon.

**Comment by rahulkgour** [comment]
> Thank you @rahulkgour .
> I think this issue is related to this [qgis/QGIS#40472](https://github.com/qgis/QGIS/issues/40472).
> Could you please try with QGIS 3.16?

**I just tried with QGIS 3.16.1**

_Got the below error and the Raster clipping process got stuck with no output._

2020-12-12T23:44:08     WARNING    Traceback (most recent call last):
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 82, in clipRastersAction
              self.clipRasters()
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 223, in clipRasters
              cfg.utls.GDALCopyRaster(vrtCheck, f, 'GTiff', cfg.rasterCompression, 'LZW')
              File "/Users/rahulgour/Library/Application Support/QGIS/QGIS3/profiles/RahulK/python/plugins/SemiAutomaticClassificationPlugin/core/utils.py", line 6923, in GDALCopyRaster
              manager = cfg.MultiManagerSCP()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/context.py", line 56, in Manager
              m.start()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/managers.py", line 567, in start
              self._address = reader.recv()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 250, in recv
              buf = self._recv_bytes()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 407, in _recv_bytes
              buf = self._recv(4)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 383, in _recv
              raise EOFError
             EOFError

**Comment by semiautomaticgit** [comment]
Thank you very much @rahulkgour 
Could you also copy the error message to https://github.com/qgis/QGIS/issues/40472

**Comment by rahulkgour** [comment]
> Thank you very much @rahulkgour
> Could you also copy the error message to [qgis/QGIS#40472](https://github.com/qgis/QGIS/issues/40472)

Done.

**Comment by semiautomaticgit** [comment]
Hello, it seems that /usr/local is not created by default.
A possible solution from https://www.facebook.com/groups/SemiAutomaticClassificationPlugin/permalink/3722826171146887/?comment_id=3740311452731692
In a Terminal: (if you have a libcrypto and libssl in /usr/local/lib this will overwrite them)
`sudo ln -sf /Library/Frameworks/Python.framework/Versions/3.9/lib/libssl.dylib /usr/local/lib/libssl.dylib
sudo ln -sf /Library/Frameworks/Python.framework/Versions/3.9/lib/libcrypto.dylib /usr/local/lib/libcrypto.dylib`
If usr/local doesn't exist, though it should, even if it's empty. Try:
`sudo mkdir -p /usr/local/lib`
Then, the ln commands and try to do processing on QGIS.

**Comment by alexkolo** [comment]
I'm having the same issue on Linux (openSUSE 15.2), using plugin version 7.8.26, qgis version 3.18.3-Zürich.

**Comment by alexkolo** [comment]
Thanks for your quick feedback. I had the same thought and already tried this, but I got the same results :( 
I (re)installed QGIS via yast2. Maybe I should try to compile it instead. I'm currently busy with some other things, but I let you know, when I get there. In any case, thanks for building such a great plugin.

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Please reopen it if it is still relevant in the new version.
Thank you!
