### ISSUE TITLE
SCP 7.2.0 Python Error 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by elpibedeliceo** [semiautomaticgit/SemiAutomaticClassificationPlugin#146]
Dear @semiautomaticgit i have this BUG when i tried to preprocess (radiometric correction and 
atmospheric correction) a Landsat Image,
the message it throws at me is the following:

TypeError: 'NoneType' object is not subscriptable 
Traceback (most recent call last):
  File "C:/Users/Maximiliano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\maininterface\landsatTab.py", line 640, in performLandsatCorrection
    self.landsat(cfg.ui.label_26.text(), o)
  File "C:/Users/Maximiliano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\maininterface\landsatTab.py", line 331, in landsat
    LDNmList = cfg.utls.findDNmin(tPMDN, NoData)
  File "C:/Users/Maximiliano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\core\utils.py", line 2006, in findDNmin
    o = cfg.utls.multiProcessRaster(rasterPath = inputRaster, functionBand = 'No', functionRaster = cfg.utls.rasterUniqueValuesWithSum, nodataValue = noDataVal, progressMessage = cfg.QtWidgetsSCP.QApplication.translate('semiautomaticclassificationplugin', 'DOS1 calculation'), deleteArray = 'No', parallel = cfg.parallelArray)
  File "C:/Users/Maximiliano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\core\utils.py", line 4791, in multiProcessRaster
    fArg = functionBandArgument[p]
**TypeError: 'NoneType' object is not subscriptable**

![error 2](https://user-images.githubusercontent.com/75565804/101277827-e6fe1c80-3795-11eb-8177-d55ec1b68dea.png)

![error 1](https://user-images.githubusercontent.com/75565804/101277830-e9f90d00-3795-11eb-94ca-24581398e35e.png)

Thanks Luca!

**Comment by semiautomaticgit** [comment]
Thank you, it should be related to this https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/145
I'll fix this

**Comment by semiautomaticgit** [comment]
It should be fixed in version 7.2.1. Please update the plugin
