### ISSUE TITLE
SCP plugin for QGIS is stuck at 50% giving the following error while trying to clip multiple rasters

### ISSUE THREAD

**Issue by R-Thirukural** [semiautomaticgit/SemiAutomaticClassificationPlugin#201]
2021-11-14T21:42:37     WARNING    Traceback (most recent call last):
              File "/Users/Thiru/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 82, in clipRastersAction
              self.clipRasters()
              File "/Users/Thiru/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 243, in clipRasters
              cfg.utls.GDALCopyRaster(vrtCheck, f, 'GTiff', cfg.rasterCompression, 'LZW')
              File "/Users/Thiru/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/core/utils.py", line 7688, in GDALCopyRaster
              manager = cfg.MultiManagerSCP()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/context.py", line 57, in Manager
              m.start()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/managers.py", line 557, in start
              self._address = reader.recv()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 255, in recv
              buf = self._recv_bytes()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 419, in _recv_bytes
              buf = self._recv(4)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 388, in _recv
              raise EOFError
             EOFError

**Comment by semiautomaticgit** [comment]
Hello @R-Thirukural ,  it could be an installation issue.
You can try to follow this guide https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#i-have-installation-issues-on-mac-os-how-can-i-install-scp-on-mac-os

**Comment by R-Thirukural** [comment]
Thank you very much @semiautomaticgit. That worked!

**Comment by semiautomaticgit** [comment]
> Thank you very much @semiautomaticgit. That worked!

You are very welcome, I'm glad it worked
