### ISSUE TITLE
[feature request] QGIS3 Compatibility

### ISSUE THREAD

**Issue by merkato** [semiautomaticgit/SemiAutomaticClassificationPlugin#23]
It's time for building QGIS3 compatibility. Creating new branch for this will be appreciated. I will help with this, as I can (not so fluent in Python yet).

**Comment by semiautomaticgit** [comment]
Thank you for your availability.
I have created the branch with the version for QGIS 3 that is already available in the QGIS experimental repository. However I'm still working on it.

**Comment by merkato** [comment]
Sidenote for Ubuntu users:
If you used QGIS2 + SCP before, then python-scipy is installed. But for QGIS3 you need python3-scipy ( `sudo apt-get install python3-scipy` )

I will test with Sentinel imagery  later today. Thanks for quick response.

**Comment by merkato** [comment]
When selecting DownloadLandsatImagesTab/DownloadSentinelImages and trying to select any position on map:

```
Traceback (most recent call last):
  File "/home/mechanik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin-scp-qgis3/maininterface/downloadlandsatpointer.py", line 51, in canvasMoveEvent
    self.moved.emit(point)
TypeError: DownloadLandsatPointer.moved[QgsPoint].emit(): argument 1 has unexpected type 'QgsPointXY'
```


On pushing find_images_toolButton in DownloadSentinelImagesTab:

```
Traceback (most recent call last):
  File "/home/mechanik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin-scp-qgis3/maininterface/downloadsentinelimages.py", line 132, in findImages
    self.queryDatabase()
  File "/home/mechanik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin-scp-qgis3/maininterface/downloadsentinelimages.py", line 661, in queryDatabase
    xml2 = response2.read()
AttributeError: 'str' object has no attribute 'read'
```

**Comment by semiautomaticgit** [comment]
Thank you.
This is due to API changes. I'll look into it.
