### ISSUE TITLE
Clipping Raster Error

### ISSUE THREAD

**Issue by emgracyn** [semiautomaticgit/SemiAutomaticClassificationPlugin#240]
Hi! I am trying to clip Landsat 8 rasters and keep getting an error with python. I am using a Mac version 12.1 and have QGIS version 3.26 and version 7 of the SCP. I am kind of new to qgis so any help/suggestions would be greatly appreciated! 

here is the log text
[log.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/9883283/log.txt)

and here is the error message I keep getting

2022-10-27T11:21:42     WARNING    Traceback (most recent call last):
              File "/Users/emmadrake/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 82, in clipRastersAction
              self.clipRasters()
              File "/Users/emmadrake/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 243, in clipRasters
              cfg.utls.GDALCopyRaster(vrtCheck, f, 'GTiff', cfg.rasterCompression, 'LZW')
              File "/Users/emmadrake/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/core/utils.py", line 7690, in GDALCopyRaster
              manager = cfg.MultiManagerSCP()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/context.py", line 57, in Manager
              m.start()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/managers.py", line 557, in start
              self._address = reader.recv()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 255, in recv
              buf = self._recv_bytes()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 419, in _recv_bytes
              buf = self._recv(4)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 388, in _recv
              raise EOFError
             EOFError
2022-10-27T11:29:38     WARNING    Traceback (most recent call last):
              File "/Users/emmadrake/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 82, in clipRastersAction
              self.clipRasters()
              File "/Users/emmadrake/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 243, in clipRasters
              cfg.utls.GDALCopyRaster(vrtCheck, f, 'GTiff', cfg.rasterCompression, 'LZW')
              File "/Users/emmadrake/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/core/utils.py", line 7690, in GDALCopyRaster
              manager = cfg.MultiManagerSCP()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/context.py", line 57, in Manager
              m.start()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/managers.py", line 557, in start
              self._address = reader.recv()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 255, in recv
              buf = self._recv_bytes()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 419, in _recv_bytes
              buf = self._recv(4)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 388, in _recv
              raise EOFError
             EOFError
2022-10-27T11:33:54     WARNING    Traceback (most recent call last):
              File "/Users/emmadrake/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 82, in clipRastersAction
              self.clipRasters()
              File "/Users/emmadrake/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 243, in clipRasters
              cfg.utls.GDALCopyRaster(vrtCheck, f, 'GTiff', cfg.rasterCompression, 'LZW')
              File "/Users/emmadrake/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/core/utils.py", line 7690, in GDALCopyRaster
              manager = cfg.MultiManagerSCP()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/context.py", line 57, in Manager
              m.start()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/managers.py", line 557, in start
              self._address = reader.recv()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 255, in recv
              buf = self._recv_bytes()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 419, in _recv_bytes
              buf = self._recv(4)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 388, in _recv
              raise EOFError
             EOFError
2022-10-27T12:01:24     WARNING    Traceback (most recent call last):
              File "/Users/emmadrake/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 82, in clipRastersAction
              self.clipRasters()
              File "/Users/emmadrake/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 243, in clipRasters
              cfg.utls.GDALCopyRaster(vrtCheck, f, 'GTiff', cfg.rasterCompression, 'LZW')
              File "/Users/emmadrake/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/core/utils.py", line 7690, in GDALCopyRaster
              manager = cfg.MultiManagerSCP()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/context.py", line 57, in Manager
              m.start()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/managers.py", line 557, in start
              self._address = reader.recv()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 255, in recv
              buf = self._recv_bytes()
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 419, in _recv_bytes
              buf = self._recv(4)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 388, in _recv
              raise EOFError
             EOFError

**Comment by semiautomaticgit** [comment]
Hello, it is an issue related to the installation of QGIS and plugin dependencies in MacOS.
You can try to follow [this guide](https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#i-have-installation-issues-on-mac-os-how-can-i-install-scp-on-mac-os)

**Comment by emgracyn** [comment]
@semiautomaticgit  if I uninstall the version of QGIS I have now will it delete the projects I have saved? Will I be able to open them with the different version of QGIS?

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Please reopen it if it is still relevant in the new version.
Thank you!
