### ISSUE TITLE
Error when drawing polygon (ROI)

### ISSUE THREAD

**Issue by raffaele-morelli** [semiautomaticgit/SemiAutomaticClassificationPlugin#242]
Hi, 

when drawing polygon I got this error
`TypeError: setAlpha(self, int): argument 1 has unexpected type 'float' 
Traceback (most recent call last):
  File "/home/rmorelli/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/dock/scpdock.py", line 2655, in clckR  
    self.addHighlightPolygon(cfg.lstROI, 1)    
  File "/home/rmorelli/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/dock/scpdock.py", line 2530, in addHighlightPolygon  
    clr.setAlpha(rT)    
TypeError: setAlpha(self, int): argument 1 has unexpected type 'float'`

QGIS running on Debian/GNU Linux

Versione Python: 3.10.8 (main, Nov  4 2022, 09:21:25) [GCC 12.2.0] 
Versione di QGIS: 3.22.12-Białowieża Białowieża, exported

**Comment by semiautomaticgit** [comment]
Hi @raffaele-morelli ,

thank you for reporting this.
It should be fixed in version 7.10.9, please update the plugin.
