### ISSUE TITLE
Uncaught TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool'


### ISSUE THREAD

**Issue by UrbanPlan-LDB** [semiautomaticgit/SemiAutomaticClassificationPlugin#254]
Impossibile caricare il plugin 'SemiAutomaticClassificationPlugin' a causa di un errore chiamando il metodo classFactory()
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-dev/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\SemiAutomaticClassificationPlugin\__init__.py", line 66, in classFactory
    return SemiAutomaticClassificationPlugin(iface)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\SemiAutomaticClassificationPlugin\semiautomaticclassificationplugin.py", line 297, in __init__
    cfg.SCPD = SCPDock()
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\SemiAutomaticClassificationPlugin\dock\scpdock.py", line 46, in __init__
    cfg.rbbrBnd = cfg.qgisGuiSCP.QgsRubberBand(cfg.cnvs, False)
TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool'

```
SemiAutomaticClassificationPlugin 7.10.10, QGIS 3.31.0-Master on Windows 10

**Comment by semiautomaticgit** [comment]
Hello @UrbanPlan-LDB , thank you for reporting this. It should be fixed in version 7.10.11, please update the plugin
