### ISSUE TITLE
Error while clipping files in SCP: Mac OS Ventura 13.2.1,  GDAL 3.4.1 , QGIS 3.28.5, Python 3.9.13

### ISSUE THREAD

**Issue by anandpethia** [semiautomaticgit/SemiAutomaticClassificationPlugin#258]
Request guidance please. facing an issue with QGIS on a MAC. Does SCP have an issue with Mac OS?

File "/Users/anand/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 82, in clipRastersAction
              self.clipRasters()
              File "/Users/anand/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 243, in clipRasters
              cfg.utls.GDALCopyRaster(vrtCheck, f, 'GTiff', cfg.rasterCompression, 'LZW')
              File "/Users/anand/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/core/utils.py", line 7686, in GDALCopyRaster
              manager = cfg.MultiManagerSCP()
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/multiprocessing/context.py", line 57, in Manager
              m.start()
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/multiprocessing/managers.py", line 557, in start
              self._address = reader.recv()
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 255, in recv
              buf = self._recv_bytes()
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 419, in _recv_bytes
              buf = self._recv(4)
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 388, in _recv
              raise EOFError
             EOFError

**Comment by anandpethia** [comment]
Tried again.

EOFError 
Traceback (most recent call last):
  File "/Users/anand/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 82, in clipRastersAction
    self.clipRasters()
  File "/Users/anand/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/maininterface/clipmultiplerasters.py", line 243, in clipRasters
    cfg.utls.GDALCopyRaster(vrtCheck, f, 'GTiff', cfg.rasterCompression, 'LZW')
  File "/Users/anand/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/core/utils.py", line 7686, in GDALCopyRaster
    manager = cfg.MultiManagerSCP()
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/multiprocessing/managers.py", line 557, in start
    self._address = reader.recv()
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError


Python version: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
QGIS version: 3.28.5-Firenze Firenze, 50adba36f2 

Python Path:
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python
/Users/anand/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/anand/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/lib-dynload
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python39.zip
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
/Users/anand/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by semiautomaticgit** [comment]
Hello, it is an installation issue. You can try to follow this guide https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#i-have-installation-issues-on-mac-os-how-can-i-install-scp-on-mac-os or use a virtual machine

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 8 of SCP.
Please reopen it if it is still relevant in the new version.
Thank you!
