### ISSUE TITLE
When i select the MTL file for Landsat data in image conversion, SCP 8.1.3 shows error message

### ISSUE THREAD

**Issue by claudioasn** [semiautomaticgit/SemiAutomaticClassificationPlugin#313]
When i select the MTL file for Landsat data in image conversion, SCP 8.1.3 shows error message: "Warning: no band found. Check metadata inside the directory". If i process without the metadata, k1 and k2 constants, for example, are not loaded.

**Comment by semiautomaticgit** [comment]
Hello, please copy the log file following these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by claudioasn** [comment]
Hello, I tried to do the process, but QGIS doesn't exactly display an error message, as in the example of the link that tells you how to report. When I try to load the MTL file in .txt, QGIS displays an alert saying that no bands were found. It's as if it wasn't communicating properly with the SCP. In addition, the .xml file (if this metadata option is selected) shows that I should load an .MTD file instead of .MTL. I select it and it doesn't seem to work properly either. To simulate the issue I'm presenting, I'd go through the following step-by-step process:

1. extract the downloaded file with the landsat 8 images (collection 2, level 1)
2. access SCP's image conversion option, select the directory with the bands (which it identifies normally)
3. try to load the metadata file

Translated with www.DeepL.com/Translator (free version)

**Comment by semiautomaticgit** [comment]
Hello @claudioasn,

> Hello, I tried to do the process, but QGIS doesn't exactly display an error message, as in the example of the link that tells you how to report. When I try to load the MTL file in .txt, QGIS displays an alert saying that no bands were found. It's as if it wasn't communicating properly with the SCP. In addition, the .xml file (if this metadata option is selected) shows that I should load an .MTD file instead of .MTL. I select it and it doesn't seem to work properly either. To simulate the issue I'm presenting, I'd go through the following step-by-step process:
> 
> 1. extract the downloaded file with the landsat 8 images (collection 2, level 1)
> 2. access SCP's image conversion option, select the directory with the bands (which it identifies normally)
> 3. try to load the metadata file

the steps are correct, it could be a system issue. Even if you don't get an error message, please copy the log file which includes more details about the running processes.

**Comment by claudioasn** [comment]
Hello, when I used the separate bands the spectral plot worked for the rois. However, when I generate a stack of bands and load it as a bandset, this problem occurs. It's as if it captured the value of only one of the bands and not all seven, showing the same value for all of them.

Could the problem be in the construction of the stack and/or when it is loaded into the bandset? I've tried saving a log file but no error is generated. It is saved empty.

Can you try to simulate this situation and see what happens for yourself? Make a bands stack, load it into bandset1, set the wavelenght, generate any roi and view the spectral plot?

Here's a screenshot of how the stack I load is configured.

![stack](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/assets/104084558/56d95a66-2946-4035-b0a7-0a475f5b55c5)

**Comment by claudioasn** [comment]
Hello @semiautomaticgit , I tried to generate the log file, but as I said, QGIS only displays a warning window when I select the MTL file, warning that "no bands were found" and that I should check my metadata. The log file saved by SCP doesn't record this information and is saved empty.

In the other topic I have open, I report how this situation may be causing problems in the generation of spectral plots and PCA.

**Comment by semiautomaticgit** [comment]
Hello @claudioasn , usually the log file should contain information about the parsing of image directory, which is useful even if there aren't error messages.
However, you should not select the MTL file if it is inside the image directories. Please try again without selection.
If the images are not found inside the directory, it could be an issue related to input images.

**Comment by claudioasn** [comment]
Hello @semiautomaticgit , adding a piece of information:

Today, I updated remotior_sensus to its new released version and tried again to reproduce the processing with level 1 data.

When doing the image conversion, the error of the MTL file in .txt continues, it does not recognize the bands. Okay, I continued processing in it and set it to run DOS.

In the new bandset generated, I went to stack the bands. And I realized that a Python error was generated when I selected the wavelenght in Band quick settings. Below is the error log:

`2023-11-17T12:15:40     WARNING    Traceback (most recent call last):
              File "C:\Users/claud/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\interface\bandset_tab.py", line 49, in satellite_wavelength
              set_satellite_wavelength()
              File "C:\Users/claud/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\interface\bandset_tab.py", line 62, in set_satellite_wavelength
              cfg.bandset_catalog.set_satellite_wavelength(
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\remotior_sensus\core\bandset_catalog.py", line 2881, in set_satellite_wavelength
              bands = bandset_x.bands
             AttributeError: 'NoneType' object has no attribute 'bands'`

Could this have anything to do with the problems I described earlier? Because the problem in generating the spectral plot, PCA and many others occurs precisely when I generate a stack. It's as if the program can't differentiate the bands, and because of this error it seems that remotior_sensus can't differentiate them or something. Then, when I generate a spectral plot, it's as if I only have the spectral response of one of the bands. The problem always occurs at stack time.

**Comment by semiautomaticgit** [comment]
Hello @claudioasn , thank you for adding information.


> When doing the image conversion, the error of the MTL file in .txt continues, it does not recognize the bands. Okay, I continued processing in it and set it to run DOS.

This is not an issue, because for Landsat SCP uses the .xml metadata file; if you select the .xml file it should work, although it is not necessary if this file is inside the same image directory.


> Could this have anything to do with the problems I described earlier? Because the problem in generating the spectral plot, PCA and many others occurs precisely when I generate a stack. It's as if the program can't differentiate the bands, and because of this error it seems that remotior_sensus can't differentiate them or something. Then, when I generate a spectral plot, it's as if I only have the spectral response of one of the bands. The problem always occurs at stack time.
Yes, at the moment there are a few issues with multiband raster in Remotior Sensus.
In the meantime you can avoid stacking bands, and create the band set using single band rasters. You can also visualize the stacked bands using the RGB color composite provided in SCP.
