### ISSUE TITLE
Scatter plot traceback

### ISSUE THREAD

**Issue by merkato** [semiautomaticgit/SemiAutomaticClassificationPlugin#32]
QGIS 2.99/SCP 6.0.2

Trying to use scatter plot, but calculate scatter plot buttons triggers traceback:

2018-02-14T11:39:08	WARNING	Traceback (most recent call last):
			  File "/home/mechanik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/spectralsignature/scatter_plot.py", line 289, in addDisplayToScatterPlot
			    self.calculatePolygonScatterPlot(pol)
			  File "/home/mechanik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/spectralsignature/scatter_plot.py", line 331, in calculatePolygonScatterPlot
			    cfg.sctrROIID_h["HISTOGRAM_" + str(cfg.sctrROIID) + "_" + str([bX, bY])] = self.calculateTempROIToScatterPlot(mL)
			  File "/home/mechanik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/spectralsignature/scatter_plot.py", line 340, in calculateTempROIToScatterPlot
			    h = cfg.utls.calculateScatterPlot(vector, "ID", str(cfg.sctrROIID), "Yes")
			  File "/home/mechanik/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/core/utils.py", line 4632, in calculateScatterPlot
			    b = cfg.utls.selectLayerbyNamecfg.bandSetsList[bandSetNumber][8]
			AttributeError: 'Utils' object has no attribute 'selectLayerbyNamecfg'

**Comment by semiautomaticgit** [comment]
Thank you very much for reporting this!
It should be fixed in 6.0.3.
