### ISSUE TITLE
When open QGIS i have warnings in Python error msg

### ISSUE THREAD

**Issue by dpoursanidis** [semiautomaticgit/SemiAutomaticClassificationPlugin#329]
2023-12-09T16:25:03     WARNING    Traceback (most recent call last):
              File "C:\Users/homoaquaticus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\semiautomaticclassificationplugin.py", line 734, in new_project_loaded
              for r in cfg.project_registry:
              File "C:\Users/homoaquaticus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\semiautomaticclassificationplugin.py", line 1672, in reset_scp
              table_w = cfg.scatter_plot_dlg.ui.scatter_list_plot_tableWidget
              File "C:\Users/homoaquaticus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\core\ui_utils.py", line 288, in set_interface
              cfg.dialog.setEnabled(state)
             RuntimeError: wrapped C/C++ object of type SemiAutomaticClassificationPluginDialog has been deleted

I have 3.28.3-Firenze and the latest version of SCP (just upgrade)

**Comment by semiautomaticgit** [comment]
Hello @dpoursanidis , usually these are installation errors.
Please try to reinstall QGIS and the plugin, then restart QGIS.

**Comment by semiautomaticgit** [comment]
I'm closing this issue. Of course please reopen this ticket if still relevant.
