### ISSUE TITLE
 The SCP plugin doesn't work at all

### ISSUE THREAD

**Issue by dzcreators** [semiautomaticgit/SemiAutomaticClassificationPlugin#361]
![Screenshot_1](https://github.com/user-attachments/assets/10925a9d-621a-427a-a8d2-45c4052da19e)

When I just opened the QGIS 3.34 application, an error notification appeared in the SCP plugin. Fill in the error as follows:

2024-07-27T20:47:48     WARNING    Traceback (most recent call last):
File "C:\Users/Mr. Maryono/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\semiautomaticclassificationplugin.py", line 765, in project_loaded
File "C:\Users/Mr. Maryono/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\semiautomaticclassificationplugin.py", line 1706, in reset_scp
File "C:\Users/Mr. Maryono/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\core\ui_utils.py", line 288, in set_interface
             RuntimeError: wrapped C/C++ object of type SemiAutomaticClassificationPluginDialog has been deleted
             
Aku sama sekali tidak paham apa yang error dalam plugin ini. Kemarin aku mencoba untuk mendownload Sentinel 2A lewat aplikasi ini dan sama sekali tidak bisa menampilkan preview maupun mendownloadnya. Selain itu, aku mencoba preprocessing file Sentinel 2A berformat jp2, namun sama sekali tidak bisa digunakan, file band sama sekali tidak bisa terbaca. Apakah ada solusi untuk hal ini?

**Comment by semiautomaticgit** [comment]
Hello @dzcreators ,
it could be an installation error.
Please update both SCP and Remotior Sensus following this guide https://semiautomaticclassificationmanual.readthedocs.io/en/latest/installation_win64.html

If you still get the same issue, please enable "Records detailed events in a log file" and copy the log file as described here https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by semiautomaticgit** [comment]
Hello @dzcreators ,
please update the SCP to version 8.3 and report if you still get the same error

**Comment by dzcreators** [comment]
![Screenshot_2](https://github.com/user-attachments/assets/12dee4bc-dcdc-4c88-abfb-0952f43743a6)

I have done according to the steps above but it still doesn't work. I also tried reinstalling QGIS and the SCP Plugin, but it still doesn't work. I tried test dependencies, the result is PyTorch: Fail as shown in the picture. Can you help again? I attached the log file too.

[File Log SCP my.txt](https://github.com/user-attachments/files/16486632/File.Log.SCP.my.txt)

**Comment by semiautomaticgit** [comment]
Hello @dzcreators ,
thank you for the log file. Probably it is a server issue.
I suggest to select the product Sentinel-2_MPC in the section "Search parameters" and try again (see https://semiautomaticclassificationmanual.readthedocs.io/en/latest/download_products_tab.html#search).

**Comment by annuva2025** [comment]
Thank you very much for the informative guidelines. I am currently facing an issue when trying to activate the classification preview pointer. The following error appears:

SCP: multiprocess: error classification

My QGIS version is 3.44.1 and SCP version is 8.5.0.
Could you please suggest a solution?

**Comment by semiautomaticgit** [comment]
You are welcome @annuva2025 .

> SCP: multiprocess: error classification

About the last error, please update the library Remotior Sensus following the same installation steps described here https://semiautomaticclassificationmanual.readthedocs.io/en/latest/installation.html
