### ISSUE TITLE
Latest version doesn't work on QGIS 3.34.11-Prizren

### ISSUE THREAD

**Issue by bbaid** [semiautomaticgit/SemiAutomaticClassificationPlugin#379]
I tried installing the plugin, but it didn't load.

Here's my QGIS version:
3.34.11-Prizren
Python version 3.12.6

I've also attached the error message QGIS gave me
[SCP-error.txt](https://github.com/user-attachments/files/17412627/SCP-error.txt)

Version 8.2.2 worked successfully|

**Comment by semiautomaticgit** [comment]
Hello @bbaid ,
it seems an installation issue.
Please try to uninstall QGIS and the plugin, then follow this guide https://semiautomaticclassificationmanual.readthedocs.io/en/latest/installation_win64.html

**Comment by semiautomaticgit** [comment]
In case of installation issues, please try this alternative method of installation dependencies https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#plugin-installation-4

**Comment by LuckyG** [comment]
I face the same error as you can see below, I already followed your suggested procedure re-installing QGIS and SCP. Please help and advise on how to fix this, thanks, Ludwig

Konnte Erweiterung 'SpatialAnalysisAgent-master' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

ModuleNotFoundError: No module named 'iface' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.15/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/ludwi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SpatialAnalysisAgent-master\__init__.py", line 35, in classFactory
    from .SpatialAnalysisAgent import SpatialAnalysisAgent
  File "C:\PROGRA~1/QGIS33~1.15/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/ludwi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SpatialAnalysisAgent-master\SpatialAnalysisAgent.py", line 31, in 
    from .SpatialAnalysisAgent_dockwidget import SpatialAnalysisAgentDockWidget
  File "C:\PROGRA~1/QGIS33~1.15/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/ludwi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SpatialAnalysisAgent-master\SpatialAnalysisAgent_dockwidget.py", line 32, in 
    import iface
  File "C:\PROGRA~1/QGIS33~1.15/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'iface'


Python-Version: 3.12.8 (main, Dec 20 2024, 15:21:15) [MSC v.1938 64 bit (AMD64)] 
QGIS-Version: 3.34.15-Prizren Prizren, 386f2583 

Python-Path:
C:\Users/ludwi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\nsq_taudem
C:\Users/ludwi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\aino-qgis-plugin-main
C:/PROGRA~1/QGIS33~1.15/apps/qgis-ltr/./python
C:/Users/ludwi/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/ludwi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.15/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS33~1.15\apps\grass\grass84\etc\python
C:\Users\ludwi\Documents
C:\Program Files\QGIS 3.34.15\bin\python312.zip
C:\PROGRA~1\QGIS33~1.15\apps\Python312\DLLs
C:\PROGRA~1\QGIS33~1.15\apps\Python312\Lib
C:\Program Files\QGIS 3.34.15\bin
C:\Users\ludwi\AppData\Roaming\Python\Python312\site-packages
C:\PROGRA~1\QGIS33~1.15\apps\Python312
C:\PROGRA~1\QGIS33~1.15\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS33~1.15\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.15\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.15\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/ludwi/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\ludwi\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\deepness\python3.12
C:\Users\ludwi\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\ludwi\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:\Users\ludwi\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:\Users\ludwi\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qfieldsync\libqfieldsync.whl
C:\Users/ludwi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing
C:\Users\ludwi\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\ludwi\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
C:\Users/ludwi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgSurf/embedded

**Comment by semiautomaticgit** [comment]
Hello @LuckyG 

> Konnte Erweiterung 'SpatialAnalysisAgent-master' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode
> 
> ModuleNotFoundError: No module named 'iface' Traceback (most recent call last): File "C:\PROGRA~1/QGIS33~1.15/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin plugins[packageName] = package.classFactory(iface) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users/ludwi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SpatialAnalysisAgent-master__init__.py", line 35, in classFactory from .SpatialAnalysisAgent import SpatialAnalysisAgent File "C:\PROGRA~1/QGIS33~1.15/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import mod = _builtin_import(name, globals, locals, fromlist, level) 

as you can see the issue is caused by a plugin called "SpatialAnalysisAgent-master", not the SCP.
