### ISSUE TITLE
error SCP when create a ROI

### ISSUE THREAD

**Issue by r2tpe** [semiautomaticgit/SemiAutomaticClassificationPlugin#42]
I got this error when create a ROI, any advice how to fix it please
----------------------------------------------------

2018-09-06T04:15:39     WARNING    Traceback (most recent call last):
              File "C:/Users/oso/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\dock\scpdock.py", line 2503, in saveROItoShapefile
              cfg.utls.calculateSignature(cfg.shpLay, cfg.bandSetsList[cfg.bndSetNumber][8], [self.ROILastID], cfg.ROIMacroID, cfg.ROIMacroClassInfo, cfg.ROIID, cfg.ROIInfo, 50, 40, "No", "No", UID)
              File "C:/Users/oso/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\core\utils.py", line 1739, in calculateSignature
              ROIsize = cfg.utls.getROISize(bX, 1, rStat[0], rStat[1])
              File "C:/Users/oso/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\core\utils.py", line 5671, in getROISize
              s = ( (a >= min) & (a              FloatingPointError: invalid value encountered in greater_equal

**Comment by semiautomaticgit** [comment]
Hello, please follow these steps to copy the plugin log file https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
If you still get the same issue, please reopen it
