### ISSUE TITLE
Error downloading Landsat data from SCP 5.4.1 on QGIS 2.18.24

### ISSUE THREAD

**Issue by PedroVenancio** [semiautomaticgit/SemiAutomaticClassificationPlugin#44]
Hi Luca, 

I'm facing this error when trying to download Landsat data from SCP 5.4.1 on QGIS 2.18.24:

```
An error has occurred while executing Python code: 

URLError: 
Traceback (most recent call last):
  File "C:/Users/PedroVenancio/.qgis2/python/plugins\SemiAutomaticClassificationPlugin\maininterface\downloadlandsatimages.py", line 155, in findImages
    self.downloadMetadata()
  File "C:/Users/PedroVenancio/.qgis2/python/plugins\SemiAutomaticClassificationPlugin\maininterface\downloadlandsatimages.py", line 204, in downloadMetadata
    searchResult = cfg.utls.NASASearch(searchUrl)
  File "C:/Users/PedroVenancio/.qgis2/python/plugins\SemiAutomaticClassificationPlugin\core\utils.py", line 322, in NASASearch
    response1 = cfg.urllib2SCP.urlopen(request1, context=newContext)
  File "C:\OSGEO4~1\apps\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\OSGEO4~1\apps\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\OSGEO4~1\apps\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\OSGEO4~1\apps\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\OSGEO4~1\apps\Python27\lib\urllib2.py", line 1241, in https_open
    context=self._context)
  File "C:\OSGEO4~1\apps\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: 

Python version: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.22 Las Palmas, 5a99678469
``` 

Trying the same search for Landsat data with SCP 6.2.3 on QGIS 3.2.3 I just get: 

`Error [39]: Unable to find images`

even with a search from 2017-01-01 or older.

Tested on Windows 10 with QGIS from OSGeo4W 64bits.

**Comment by semiautomaticgit** [comment]
Hi Pedro,

thank you for reporting this.
I'll look into this.

Best regards

**Comment by semiautomaticgit** [comment]
Hi Pedro,

it should be fixed in the latest version.
Best

**Comment by PedroVenancio** [comment]
Thank you very much Luca!!

**Comment by semiautomaticgit** [comment]
You are very welcome
