### ISSUE TITLE
Accuracy Assessment produces problem

### ISSUE THREAD

**Issue by jcf7140** [semiautomaticgit/SemiAutomaticClassificationPlugin#55]
Hi there

I've tried the accuracy assessment for the first time today, but unfortunately it's not working. 
I followed the steps as set out in an online tutorial and made sure that both my raster and reference vector file is in the correct format. 
However, everytime I run the process, QGIS gives me the following error message and stops processing: 

2019-03-11T15:02:59     WARNING    Traceback (most recent call last):
              File "C:/Users/Jcf.7140/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\maininterface\accuracy.py", line 48, in calculateErrorMatrix
              self.errorMatrix(self.clssfctnNm, cfg.referenceLayer)
              File "C:/Users/Jcf.7140/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\maininterface\accuracy.py", line 154, in errorMatrix
              cfg.utls.vectorToRaster(fd, str(l.source()), classification, str(tRC))
              File "C:/Users/Jcf.7140/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\core\utils.py", line 5984, in vectorToRaster
              referenceRasterName = cfg.bandSetsList[cfg.bndSetNumber][3][0]
             IndexError: list index out of range

Any assistance will be much appreciated!!

**Comment by semiautomaticgit** [comment]
Hello, it seems an issue related to the vector. Please check that the coordinate reference system is the same for both data. 
Also, please follow these steps https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by jcf7140** [comment]
Hi Luca
Thanks for the quick feedback. 
I've checked the CRS of both datasets and they're identical. 
I have also followed the steps on the link you provided and have the log file and error message ready - just waiting to be accepted onto you Fb group. 

Thank you for providing one of the best plugins I've ever used in QGIS!

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
If you still get the same issue, please reopen it
