### ISSUE TITLE
Floating point error

### ISSUE THREAD

**Issue by asdelossantos** [semiautomaticgit/SemiAutomaticClassificationPlugin#56]
2019-04-05T00:29:33     WARNING    Traceback (most recent call last):
              File "C:/Users/ASUS/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\dock\scpdock.py", line 2503, in saveROItoShapefile
              cfg.utls.calculateSignature(cfg.shpLay, cfg.bandSetsList[cfg.bndSetNumber][8], [self.ROILastID], cfg.ROIMacroID, cfg.ROIMacroClassInfo, cfg.ROIID, cfg.ROIInfo, 50, 40, "No", "No", UID)
              File "C:/Users/ASUS/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\core\utils.py", line 1739, in calculateSignature
              ROIsize = cfg.utls.getROISize(bX, 1, rStat[0], rStat[1])
              File "C:/Users/ASUS/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\core\utils.py", line 5672, in getROISize
              s = ( (a >= min) & (a              **FloatingPointError: invalid value encountered in greater_equal**

**Comment by asdelossantos** [comment]
![Untitled](https://user-images.githubusercontent.com/49284900/55594996-7444ce80-5774-11e9-8dc0-b17299368751.png)

**Comment by semiautomaticgit** [comment]
Hello, 
please follow these steps to copy the SCP log file https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
If you still get the same issue, please reopen it
