### ISSUE TITLE
Eigenvalues do not converge when running PCA

### ISSUE THREAD

**Issue by wguthe** [semiautomaticgit/SemiAutomaticClassificationPlugin#64]
When trying to run PCA on a Sentinel2 image, it stops at a covariance step with the following:

An error has occurred while executing Python code: 

numpy.linalg.LinAlgError: Eigenvalues did not converge 
Traceback (most recent call last):
  File "C:/Users/wguthe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\maininterface\pcaTab.py", line 46, in calculatePCAAction
    self.calculatePCA()
  File "C:/Users/wguthe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\maininterface\pcaTab.py", line 97, in calculatePCA
    self.PCACalculation(rD, bL, outF, numbComp, None, batch)
  File "C:/Users/wguthe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\maininterface\pcaTab.py", line 140, in PCACalculation
    comp, totalVariance, totalVarianceCumulative, eigenValues = self.calculateEigenVectors(covM)
  File "C:/Users/wguthe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SemiAutomaticClassificationPlugin\maininterface\pcaTab.py", line 264, in calculateEigenVectors
    val, vect = cfg.np.linalg.eigh(matrix)
  File "C:\OSGeo4W64\apps\Python37\lib\site-packages\numpy\linalg\linalg.py", line 1456, in eigh
    w, vt = gufunc(a, signature=signature, extobj=extobj)
  File "C:\OSGeo4W64\apps\Python37\lib\site-packages\numpy\linalg\linalg.py", line 103, in _raise_linalgerror_eigenvalues_nonconvergence
    raise LinAlgError("Eigenvalues did not converge")
numpy.linalg.LinAlgError: Eigenvalues did not converge

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.4.8-Madeira Madeira, 04ee8e0761

**Comment by semiautomaticgit** [comment]
Hello, is the image clipped or converted to reflectance?
Also, please follow these steps to copy the log file https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by wguthe** [comment]
Hi, Luca.  Thank you for responding to this.  I don’t use Facebook, so I’ll just send you the debug and error messages this way.

I didn’t clip the image, but I did run the Pre-processing step for Sentinel2 (that part completed without a problem) and ran the PCA on the band set that was generated by the pre-processing. The PCA died on one of the last covariance steps.

I can send you the imagery itself, or try the same steps on the sample data you have a link to.

Thanks,
Bill G

**Comment by semiautomaticgit** [comment]
Hello, it seems an issue related to permissions. Please that there is enough disk space and check if any antivirus is blocking the process.
Also check that the band set is composed of .tif files only.

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
If you still get the same issue, please reopen it
